# Generated by Django 3.2.5 on 2021-07-24 17:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('categories', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='A description of the quiz', verbose_name='వివరణ')),
                ('quiz_type', models.CharField(choices=[('configured', 'నిర్దిష్టమయిన'), ('dynamic', 'క్రియాశీలక')], db_index=True, default='dynamic', max_length=16, verbose_name='ప్రశ్నల పరీక్ష రకం')),
                ('maximum_number_of_questions', models.PositiveIntegerField(default=10, verbose_name='ప్రశ్నల గరిష్ట సంఖ్య')),
                ('maximum_marks', models.PositiveIntegerField(default=10, verbose_name='గరిష్ట మార్కులు')),
                ('maximum_bonus_marks', models.PositiveIntegerField(default=10, verbose_name='గరిష్ట బహుమాన మార్కులు')),
                ('is_published', models.BooleanField(default=False, verbose_name='ప్రచురించబడిందా?')),
                ('display_order', models.PositiveIntegerField(verbose_name='ప్రదర్శన క్రమం')),
                ('random_order', models.BooleanField(default=False, help_text='ప్రశ్నలను యాదృచ్ఛిక క్రమంలో ప్రదర్శించాలా లేదా అవి పొందుపరిచిన క్రమంలో ప్రదర్శించాలా?', verbose_name='యాదృచ్ఛిక క్రమం')),
                ('pass_mark', models.SmallIntegerField(blank=True, default=0, help_text='పరీక్షలో ఉత్తీర్ణత సాధించాల్సిన శాతం.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='ఉత్తీర్ణత సాధించాల్సిన మార్కు')),
                ('success_text', models.TextField(blank=True, help_text='వినియోగదారు ఉత్తీర్ణులైతే ప్రదర్శించబడుతుంది.', verbose_name='విజయ వచనం')),
                ('fail_text', models.TextField(blank=True, help_text='వినియోగదారు విఫలమైతే ప్రదర్శించబడుతుంది.', verbose_name='వైఫల్యం వచనం')),
                ('answers_at_end', models.BooleanField(default=False, help_text='ప్రశ్న తర్వాత సరైన సమాధానం చూపబడదు. సమాధానాలు చివరిలో ప్రదర్శించబడతాయి.', verbose_name='చివరికి సమాధానాలు')),
                ('exam_paper', models.BooleanField(default=False, help_text='అవును అయితే, వినియోగదారు చేసిన ప్రతి ప్రయత్నం ఫలితం నిల్వ చేయబడుతుంది. మార్కింగ్ కోసం అవసరం.', verbose_name='పరీక్షా పత్రం')),
                ('ask_till_all_correct', models.BooleanField(default=False, help_text='User should answer all questions.', verbose_name='Ask till all correct')),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='వర్గం')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language', verbose_name='Language')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('display_order', models.PositiveIntegerField(verbose_name='ప్రదర్శన క్రమం')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionset', verbose_name='Quiz Set')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz', verbose_name='ప్రశ్నల పరీక్ష')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('display_order', models.PositiveIntegerField(verbose_name='ప్రదర్శన క్రమం')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='ప్రశ్నల పరీక్ష')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz', verbose_name='ప్రశ్నల పరీక్ష')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set',
            field=models.ManyToManyField(blank=True, through='quizzes.QuizQuestionSet', to='questions.QuestionSet'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(through='quizzes.QuizQuestion', to='questions.Question'),
        ),
    ]
