# Generated by Django 3.2.5 on 2021-07-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ప్రదర్శన క్రమం'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exam_paper',
            field=models.BooleanField(default=False, help_text='అవును అయితే, వినియోగదారు చేసిన ప్రతి ప్రయత్నం ఫలితం నిల్వ చేయబడుతుంది. మూల్యాంకనము కోసం అవసరం.', verbose_name='పరీక్షా పత్రం'),
        ),
    ]
