# Generated by Django 3.2.5 on 2021-07-25 12:25

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210725_1115'),
        ('quizzes', '0004_auto_20210725_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionSetQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ప్రదర్శన క్రమం')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='ప్రశ్నల పరీక్ష')),
                ('quiz_question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizquestionset', verbose_name='Quiz Quiz Set')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quizquestionset',
            name='questions',
            field=models.ManyToManyField(blank=True, through='quizzes.QuizQuestionSetQuestion', to='questions.Question'),
        ),
    ]
