# Generated by Django 3.2.5 on 2021-07-25 21:48

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, max_length=255, populate_from='title', unique=True, verbose_name='స్లగ్'),
        ),
    ]
