# Generated by Django 3.2.5 on 2021-07-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quiz_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='maximum_number_of_user_attempts',
            field=models.PositiveIntegerField(default=100, verbose_name='Maximum number of user attempts'),
        ),
    ]
