# Generated by Django 3.2.5 on 2021-08-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_quiz_maximum_number_of_user_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date_removed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted?'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='date_removed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted?'),
        ),
        migrations.AddField(
            model_name='quizquestionset',
            name='date_removed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quizquestionset',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted?'),
        ),
        migrations.AddField(
            model_name='quizquestionsetquestion',
            name='date_removed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quizquestionsetquestion',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted?'),
        ),
    ]
