# Generated by Django 3.2.5 on 2021-12-23 05:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20210804_0446'),
        ('questions', '0006_auto_20211223_0513'),
        ('quizzes', '0009_auto_20210804_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answers_at_end',
            field=models.BooleanField(default=False, help_text='Correct answer is NOT shown after question. Answers displayed at the end.', verbose_name='Answers at end'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the quiz', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exam_paper',
            field=models.BooleanField(default=False, help_text='If yes, the result of each attempt by a user will be stored. Necessary for marking.', verbose_name='Exam Paper'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fail_text',
            field=models.TextField(blank=True, help_text='Displayed if user fails.', verbose_name='Fail Text'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Has been published?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='maximum_bonus_marks',
            field=models.PositiveIntegerField(default=10, verbose_name='Maximum bonus marks'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='maximum_marks',
            field=models.PositiveIntegerField(default=10, verbose_name='Maximum marks'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='maximum_number_of_questions',
            field=models.PositiveIntegerField(default=10, verbose_name='Maximum number of questions'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_mark',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Percentage required to pass exam.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Pass Mark'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('adaptive', 'Adaptive'), ('configured', 'Configured'), ('dynamic', 'Dynamic')], db_index=True, default='dynamic', max_length=16, verbose_name='Quiz type'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=False, help_text='Display the questions in a random order or as they are set?', verbose_name='Random Order'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, max_length=255, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='success_text',
            field=models.TextField(blank=True, help_text='Displayed if user passes.', verbose_name='Success Text'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizquestionset',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='quizquestionset',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizquestionsetquestion',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='quizquestionsetquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Quiz'),
        ),
    ]
