-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
        exclude: \.css$
    -   id: check-merge-conflict
    -   id: check-json
    -   id: debug-statements
    -   id: check-added-large-files
        args:
        - --maxkb=500
    -   id: flake8
        args:
        - --max-line-length=79
        - --ignore=W503
        exclude: (tests/.*|.*/migrations/.*\.py)$
    -   id: flake8
        name: Flake8 migrations
        args:
        - --ignore=N806,E501,W503
        - --max-line-length=131
        files: (.*/migrations/.*\.py)$
    -   id: flake8
        name: Flake8 tests
        args:
        - --ignore=F811,W503
        - --max-line-length=131
        files: (tests/.*\.py)$
-   repo: local
    hooks:
    -   id: isort
        name: Sorting Imports
        entry: isort
        language: system
        files: \.py$
        exclude: (.*/scripts/.*|.*/migrations/.*)$
