# Generated by Django 3.2.5 on 2021-07-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
    ]
