# Generated by Django 3.2.5 on 2021-08-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210724_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='english_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='English name'),
        ),
    ]
