# Generated by Django 3.2.5 on 2021-08-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_removed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted?'),
        ),
    ]
