# Generated by Django 3.2.5 on 2021-07-17 00:05

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('two_letter_code', models.CharField(max_length=5)),
                ('three_letter_code', models.CharField(max_length=5)),
                ('display_order', models.PositiveIntegerField(verbose_name='Display order')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
