# Generated by Django 3.2.5 on 2021-07-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='language',
            name='english_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='three_letter_code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='two_letter_code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
