# Generated by Django 3.2.5 on 2021-07-22 18:41

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_correct', models.BooleanField(default=False, verbose_name='ఈ ప్రయత్నం సరైనదేనా?')),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='వచ్చిన మార్కులు')),
                ('is_evaluated', models.BooleanField(default=False, verbose_name='Is evaluated?')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date and time?')),
                ('final_submission_info', models.JSONField(default=dict, verbose_name=' info')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('questions_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=40, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Questions list')),
                ('completed_question_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=40, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Completed question list')),
                ('not_completed_question_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=40, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Not completed question list')),
                ('incorrect_question_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=40, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Incorrect questions list')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='మొత్తం స్కోరు')),
                ('current_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Current Score')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is completed?')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date and time?')),
                ('final_submission_info', models.JSONField(default=dict, verbose_name=' info')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
