# Generated by Django 3.2.5 on 2021-07-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0002_alter_sentence_options'),
        ('quiz_attempts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptedquestion',
            name='entered_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sentences.sentence', verbose_name='వాక్యం'),
        ),
    ]
