# Generated by Django 3.2.5 on 2021-07-25 12:59

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_attempts', '0003_alter_attemptedquestion_entered_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_question_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=40, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Completed question list'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='incorrect_question_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=40, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Incorrect questions list'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='not_completed_question_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=40, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Not completed question list'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='questions_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=40, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Questions list'),
        ),
    ]
