# Generated by Django 3.2.5 on 2021-07-31 19:03

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_attempts', '0006_quizattempt_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True, verbose_name='modified'),
        ),
    ]
