# Generated by Django 3.2.5 on 2021-08-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_attempts', '0007_auto_20210731_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptedquestion',
            name='date_removed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptedquestion',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted?'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='date_removed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted?'),
        ),
    ]
