# Generated by Django 3.2.5 on 2021-12-23 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0003_auto_20210804_0446'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0009_auto_20210804_0446'),
        ('quiz_attempts', '0008_auto_20210804_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptedquestion',
            name='entered_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sentences.sentence', verbose_name='Sentence'),
        ),
        migrations.AlterField(
            model_name='attemptedquestion',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Was this attempt correct?'),
        ),
        migrations.AlterField(
            model_name='attemptedquestion',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Marks Obtained'),
        ),
        migrations.AlterField(
            model_name='attemptedquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Score'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
