# Generated by Django 3.2.5 on 2021-07-22 18:41

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sentences', '0001_initial'),
        ('languages', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('question_type', models.CharField(choices=[('mcq', 'బహుళ ఎంపిక జవాబు ప్రశ్న'), ('mcmq', 'బహుళ ఎంపిక బహుళ జవాబు ప్రశ్న'), ('jwq', 'గందరగోళ పద జవాబు ప్రశ్న'), ('trq', 'అనువాద ప్రశ్న'), ('tq', 'Textual question')], db_index=True, default='mcq', max_length=16, verbose_name='ప్రశ్న రకం')),
                ('maximum_marks', models.DecimalField(decimal_places=2, default=4, max_digits=6, verbose_name='గరిష్ట మార్కులు')),
                ('is_published', models.BooleanField(default=False, verbose_name='ప్రచురించబడిందా?')),
                ('display_order', models.PositiveIntegerField(verbose_name='ప్రదర్శన క్రమం')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='వర్గం')),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_correct_answers', to='sentences.sentence', verbose_name='Correct answer')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language', verbose_name='Language')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sentences.sentence', verbose_name='Sentence')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='A description of the QuestionSet', verbose_name='వివరణ')),
                ('display_order', models.PositiveIntegerField(verbose_name='ప్రదర్శన క్రమం')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_correct', models.BooleanField(default=False, verbose_name='ఈ సమాధానం సరైనదేనా?')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language', verbose_name='Language')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentences.sentence', verbose_name='Sentence')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
