# Generated by Django 3.2.5 on 2021-07-24 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0002_alter_sentence_options'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'ప్రశ్నలు'},
        ),
        migrations.AlterModelOptions(
            name='questionset',
            options={'verbose_name': 'Question set', 'verbose_name_plural': 'Question sets'},
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the Question', verbose_name='వివరణ'),
        ),
        migrations.AddField(
            model_name='question',
            name='hint_text',
            field=models.TextField(blank=True, help_text='A message that will be shown if this question is not answered correctly.', verbose_name='Hint text'),
        ),
        migrations.AddField(
            model_name='question',
            name='success_text',
            field=models.TextField(blank=True, help_text='A message that will be shown after successfully answering the question.', verbose_name='Success text'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentences.sentence', verbose_name='వాక్యం'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_correct_answers', to='sentences.sentence', verbose_name='Correct answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ప్రదర్శన క్రమం'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sentences.sentence', verbose_name='వాక్యం'),
        ),
    ]
