# Generated by Django 3.2.5 on 2021-12-23 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20210804_0446'),
        ('sentences', '0003_auto_20210804_0446'),
        ('questions', '0005_auto_20210804_0446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is this answer correct?'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentences.sentence', verbose_name='Sentence'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the Question', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Has been published?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='maximum_marks',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=6, verbose_name='Maximum Marks'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple choice answer question'), ('mcmq', 'Multiple choice multiple answer question'), ('jwq', 'Jumble words answer question'), ('swq', 'Single word answer question'), ('trq', 'Translation question'), ('tq', 'Textual question')], db_index=True, default='mcq', max_length=16, verbose_name='Question type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sentences.sentence', verbose_name='Sentence'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the QuestionSet', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
    ]
