# Generated by Django 3.2.5 on 2021-07-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'verbose_name': 'Sentence', 'verbose_name_plural': 'Sentences'},
        ),
    ]
