# Generated by Django 3.2.5 on 2021-12-23 05:13

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_auto_20210804_0446'),
        ('sentences', '0003_auto_20210804_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='translations',
        ),
        migrations.CreateModel(
            name='SentenceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted?')),
                ('date_removed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentences.sentence')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sentences.sentence')),
            ],
            options={
                'verbose_name': 'Sentence Translation',
                'verbose_name_plural': 'Sentence Translations',
            },
        ),
    ]
