# Generated by Django 3.2.5 on 2021-07-22 18:41

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sentences', '0001_initial'),
        ('languages', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('credits', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.ImageField(blank=True, max_length=256, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, to='categories.Category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentences.sentence')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
